# Generated by Django 3.2.12 on 2022-03-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('todo_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='table',
        ),
    ]
